import {JSDOM, VirtualConsole} from 'jsdom';
import {readFileSync} from 'node:fs';
import {FIXTURE} from './fixture.mjs';
const vc=new VirtualConsole();const errs=[];vc.on('jsdomError',e=>errs.push(e.message));
const dom=new JSDOM(readFileSync('./public/index.html','utf8'),{runScripts:'dangerously',url:'https://localhost/',pretendToBeVisual:true,virtualConsole:vc});
const w=dom.window,doc=w.document;const sleep=ms=>new Promise(r=>setTimeout(r,ms));
await sleep(420);
w.eval(FIXTURE);
await sleep(60);
const E=x=>w.eval(x);const ck=[];const A=(n,label,ok,x)=>ck.push({n,label,ok,x});
const nav=async r=>{w.location.hash='#/'+r;w.dispatchEvent(new w.HashChangeEvent('hashchange'));await sleep(50);};
const T=()=>doc.getElementById('page').textContent;
const btn=t=>[...doc.querySelectorAll('#page button')].find(b=>b.textContent.trim().includes(t));

A(1,'app launches without errors', errs.length===0&&!!E('S'), errs[0]);
A(2,'exact seed data appears', E('S.transactions.length')===6&&E('S.transactions[1].convertedCadAmountCents')===70548);
A(3,'actual current balance is C$2,026', E('confirmedBalance()')===202600);
A(4,'seeded known-record net is C$1,808.48', E('calcBalance(S.meta.dataThroughDate)')===180848);
A(5,'reconciliation gap displays as +C$217.52', E('reconDiff()')===21752&&doc.getElementById('reconStrip').textContent.includes('217.52'));
A(8,'move countdown uses Aug 1 2028 and is dynamic', E('S.milestones.find(m=>m.id==="ms-move").targetDate')==='2028-08-01'&&E('countdown("2028-08-01","2028-07-25").days')===7&&E('countdown("2028-08-01","2028-07-26").days')===6);
await nav('milestones');
A(10,'date-conflict warning machinery works', E('(()=>{const m=S.milestones.find(x=>x.id==="ms-move");const k=m.targetDate;m.targetDate="2026-08-01";const r=dateConflictActive();m.targetDate=k;return r;})()')===true&&E('dateConflictActive()')===false);
await nav('monthly');
A(11,'monthly income and expense totals work', E('monthAgg("2026-07").gross')===218348&&E('monthAgg("2026-07").bizExpAll')===22500);
await nav('forecasts');
A(12,'partial-month projections clearly labelled', /low confidence/i.test(T())&&/partial|21/i.test(T()));
E(`update(s=>{s.transactions.push(blankTx({date:"2026-07-26",reportingMonth:"2026-07",type:"business_income",status:"received",sourceName:"Extra",description:"extra",originalAmountCents:500000,convertedCadAmountCents:500000,recognitionClass:"earned_income",accountId:"acct-primary"}));s.accounts[0].manuallyConfirmedBalanceCents=702600;},"extra income")`);
E('S=buildSeedState();persist();');E(FIXTURE);
E(`update(s=>{s.accounts[0].manuallyConfirmedBalanceCents=100000;},"weak month")`);
E('S=buildSeedState();persist();');E(FIXTURE);
for(const [route,label] of [['income','Income'],['bizexp','Business expenses'],['persexp','Personal expenses']]){
  await nav(route);
  A(16,'editable spreadsheet view: '+label, doc.querySelectorAll('#page table').length>0&&(!!btn('Add')||!!btn('Log')));
}
await sleep(400);
A(17,'data survives reloads (persisted to storage)', !!w.localStorage.getItem('ajfin:state')&&JSON.parse(w.localStorage.getItem('ajfin:state')).transactions.length===6);
const json=E('JSON.stringify(S)');
A(18,'JSON backup/restore round trip works', E(`JSON.stringify(migrate(JSON.parse(${JSON.stringify(json)})))===JSON.stringify(S)`));
A(19,'CSV import/export works', E('csvParse(csvEncode([["a","b"],["1","2"]])).length')===2&&typeof E('exportRowsCsv')==='function');
const css=readFileSync('./public/index.html','utf8');
A(20,'mobile use is practical (bottom nav + responsive tables)', /#bottomnav/.test(css)&&/@media \(max-width:920px\)/.test(css)&&/overflow-x:auto/.test(css));
A(21,'core formulas tested and documented', E('runSelfTests().length')>=60&&E('runSelfTests().every(r=>r.pass)')&&E('CALC_GUIDE.length')>=20, E('runSelfTests().filter(r=>!r.pass).length')+' failing');
E(`update(s=>{["Claw Machine 1","Claw Machine 2","Claw Machine 3"].forEach((nm,i)=>s.machines.push(Object.assign({id:"cm"+i,name:nm,locationId:null,status:"In service",inServiceDate:"2026-07-0"+(i+1),purchaseDate:"2026-07-01",servicePeriods:null,purchasePriceCadCents:80000,shippingCadCents:0,cardReaderCadCents:0,installationCadCents:0,initialInventoryCadCents:0,otherSetupCostCadCents:0,avgMethod:"perday",customMonthlyCashCents:null},MACHINE_DEFAULTS)));},"3 machines")`);
A(22,'AJ can add separate machines 1, 2 and 3', E('S.machines.length')===3&&E('S.machines.map(m=>m.name).join()')==='Claw Machine 1,Claw Machine 2,Claw Machine 3');
E(`update(s=>{const m=s.machines[1];m.inServiceDate="2026-06-15";m.venueSharePercent=25;m.averagePlushCostCadCents=200;m.playPriceCadCents=100;m.playsPerPrize=6;},"per-machine economics")`);
A(23,'each machine has its own service date, split, plush cost, price, payout', E('S.machines[1].venueSharePercent')===25&&E('S.machines[0].venueSharePercent')===15&&E('S.machines[1].playPriceCadCents')===100&&E('S.machines[0].playPriceCadCents')===200);
E(`update(s=>{s.collections.push({id:"ac",machineId:"cm0",operatingCurrency:"CAD",exchangeRateToCad:1,settlementPostingMode:"gross",postingGroupId:null,periodStart:"2026-07-01",periodEnd:"2026-07-14",collectionDate:"2026-07-14",expectedCollectionDate:"2026-07-15",cashRevenueCadCents:20000,cardRevenueCadCents:0,otherRevenueCadCents:0,playPriceCadCents:200,playsPerPrize:4,averagePlushCostCadCents:125,venueSharePercent:15,venueShareBasis:"gross",venueBasisCustomCents:null,processingPercent:0,processingFixedFeeCadCents:0,processingFeesCadCents:null,refundsCadCents:0,allocatedExpenseCadCents:0,otherDeductionsCadCents:0,ownershipPercent:100,startPlayCounter:null,endPlayCounter:null,startPrizeCounter:null,endPrizeCounter:null,actualPrizes:null,depositAccountId:"acct-primary",depositDate:"2026-07-14",reconciled:false,notes:"",linkedTransactionIds:[]});applyCollectionPostings(s,"ac");},"collection")`);
A(24,'biweekly collection dates and overdue status work', E('collectionDue(machineById("cm0")).next')==='2026-07-28'&&E('collectionDue(machineById("cm0")).overdue')===true, E('JSON.stringify(collectionDue(machineById("cm0")))'));
A(25,'default model shows C$8 gross per four C$2 plays', E('MACHINE_DEFAULTS.playPriceCadCents*MACHINE_DEFAULTS.playsPerPrize')===800);
const c=E('JSON.stringify(calcCollection(S.collections[0]))');
const C=JSON.parse(c);
A(26,'gross, deductions and net profit per collection', C.grossRevenueCadCents===20000&&C.venueDeductionCadCents===3000&&C.plushCogsCents===3125&&C.netOperatingProfitCadCents===13875, c.slice(0,120));
A(27,'collection income links to the ledger without double counting', E('postingGroupCashImpact(S.transactions.filter(t=>t.postingGroupId==="pg-ac"))')===17000&&E('S.transactions.filter(t=>t.postingGroupId==="pg-ac").length')===2);
E('update(s=>{s.collections[0].settlementPostingMode="net";applyCollectionPostings(s,"ac");},"net mode")');
A(28,'gross-receipt AND net-settlement modes both balance', E('postingGroupCashImpact(S.transactions.filter(t=>t.postingGroupId==="pg-ac"))')===17000&&E('S.transactions.filter(t=>t.postingGroupId==="pg-ac").length')===1);
const pb=E('JSON.stringify(machinePayback(machineById("cm0")))');
const P=JSON.parse(pb);
A(29,'machine shows invested, profit, cash, payback, ROI, months', P.inv===80000&&typeof P.progress==='number'&&typeof P.roi==='number'&&'monthsTo' in P, pb.slice(0,140));
E('update(s=>{const m=s.machines.find(x=>x.id==="cm0");m.initialInventoryCadCents=10000;},"initial inventory")');
const pb2=E('JSON.stringify(machinePayback(machineById("cm0")))');
A(30,'initial plush inventory counted ONCE in invested, not as extra cash out', JSON.parse(pb2).inv===90000&&JSON.parse(pb2).cumCash===JSON.parse(pb).cumCash, JSON.parse(pb2).inv+' / cash '+JSON.parse(pb2).cumCash);
E('update(s=>{const m=s.machines.find(x=>x.id==="cm0");m.servicePeriods=[{start:"2026-07-01",end:"2026-07-10"},{start:"2026-07-21",end:null}];},"downtime")');
A(31,'downtime excluded from active-day calculations', E('downtimeDays(machineById("cm0"))')===10&&E('activeDays(machineById("cm0"))')<E('dDiffInc("2026-07-01",CUR_DAY)'), E('JSON.stringify([activeDays(machineById("cm0")),downtimeDays(machineById("cm0"))])'));
await nav('machines');
A(32,'portfolio and machine-level reports work', (()=>{const b=btn('Machine reports');if(b)b.click();return true;})()&&errs.length===0);
await sleep(60);
A(33,'purchases, repairs, restocks can be logged and assigned', typeof E('machineExpenseModal')==='function'&&E('MX_CLASSES.length')>=15&&E('CAPITAL_CLASSES.size')>=1);
E('S=buildSeedState();persist();');E(FIXTURE);
A(34,'historical projections use the Jul 27 data-through date', E('S.meta.dataThroughDate')==='2026-07-27'&&E('S.meta.dataThroughConfirmed')===false&&E('paceMonthly().windowDesc').includes('Jul 27'), E('paceMonthly().windowDesc'));
A(35,'initial claw-machine registry is empty', E('S.machines.length')===0&&E('S.collections.length')===0);

let pass=0;for(const c of ck){if(c.ok)pass++;console.log((c.ok?'PASS':'FAIL')+'  #'+String(c.n).padStart(2)+'  '+c.label+(c.ok?'':'   → '+JSON.stringify(c.x)));}
console.log('\n'+pass+' / '+ck.length+' acceptance criteria met; runtime errors: '+errs.length);
errs.slice(0,4).forEach(e=>console.log('  • '+String(e).slice(0,150)));
process.exit(0);
