import {JSDOM, VirtualConsole} from 'jsdom';
import {readFileSync} from 'node:fs';
import {FIXTURE} from './fixture.mjs';
const vc=new VirtualConsole();const errs=[];vc.on('jsdomError',e=>errs.push(e.message));
const dom=new JSDOM(readFileSync('./public/index.html','utf8'),{runScripts:'dangerously',url:'https://localhost/',pretendToBeVisual:true,virtualConsole:vc});
const w=dom.window,doc=w.document;const sleep=ms=>new Promise(r=>setTimeout(r,ms));
await sleep(420);
w.eval(FIXTURE);
await sleep(60);
const E=x=>w.eval(x);const ch=[];const ck=(n,ok,x)=>ch.push({n,ok,x});
w.location.hash='#/importexport';w.dispatchEvent(new w.HashChangeEvent('hashchange'));await sleep(80);
// paste a messy but realistic CSV: BOM, CRLF, quoted comma, currency symbols, blank line
const csv='\ufeffDate,Description,Payee,Amount\r\n2026-08-03,"Placement, August",Acme Arcade,"$310.00"\r\n2026-08-05,Boba venue,Tea House,275.50\r\n\r\nbadrow,,,notanumber\r\n';
const ta=doc.querySelector('#page textarea');
ck('import wizard offers a paste box', !!ta);
ta.value=csv; ta.dispatchEvent(new w.Event('change',{bubbles:true}));
await sleep(120);
const t=()=>doc.getElementById('page').textContent;
ck('header auto-mapping worked despite the BOM', t().includes('Date') && !t().includes('\ufeffDate'), t().slice(0,120));
ck('2 importable rows detected', /2 importable/.test(t()), t().match(/\d+ importable[^,]*/));
ck('1 error row reported with a reason', /1 error row/.test(t()), t().match(/\d+ error row[^:]*/));
ck('quoted comma kept inside the description', t().includes('Placement, August'));
ck('currency symbol parsed to 310.00', t().includes('310.00'));
const before=E('S.transactions.length');
const imp=[...doc.querySelectorAll('#page button')].find(b=>/^Import \d+ rows$/.test(b.textContent.trim()));
ck('import button shows a count', !!imp, imp&&imp.textContent);
imp.click(); await sleep(200);
ck('rows actually imported', E('S.transactions.length')===before+2, E('S.transactions.length')+' vs '+(before+2));
ck('imported amounts are exact cents', E('S.transactions.filter(t=>t.sourceName==="Acme Arcade")[0].convertedCadAmountCents')===31000, E('S.transactions.filter(t=>t.sourceName==="Acme Arcade").map(t=>t.convertedCadAmountCents)'));
ck('no runtime errors during import', errs.length===0, errs[0]);
let pass=0;for(const c of ch){if(c.ok)pass++;console.log((c.ok?'PASS':'FAIL')+'  '+c.n+(c.ok?'':'   → '+JSON.stringify(c.x)));}
console.log('\n'+pass+' / '+ch.length+' CSV import checks; runtime errors: '+errs.length);
process.exit(0);
