import {JSDOM} from 'jsdom';
import {readFileSync} from 'node:fs';
import {FIXTURE} from './fixture.mjs';
const html=readFileSync('./public/index.html','utf8');
const errors=[];const vc=new (await import('jsdom')).VirtualConsole();
vc.on('jsdomError',e=>errors.push(e.stack||e.message));vc.on('error',(...a)=>errors.push(a.join(' ')));
const dom=new JSDOM(html,{runScripts:'dangerously',url:'https://localhost/',pretendToBeVisual:true,virtualConsole:vc});
const w=dom.window,doc=w.document;const sleep=ms=>new Promise(r=>setTimeout(r,ms));
await sleep(420);
w.eval(FIXTURE);
await sleep(60);
const btn=(t,root)=>[...(root||doc).querySelectorAll('button')].find(b=>b.textContent.trim().includes(t));
w.location.hash='#/machines';w.dispatchEvent(new w.HashChangeEvent('hashchange'));await sleep(40);
btn('Add claw machine').click();await sleep(40);
let modal=doc.querySelector('#modalhost .modal');
console.log('modal open:',!!modal);
btn('Add machine',modal).click();await sleep(80);
console.log('modal after add:',!!doc.querySelector('#modalhost .modal'));
console.log('page head:',doc.getElementById('page').textContent.slice(0,300).replace(/\s+/g,' '));
console.log('buttons:',[...doc.querySelectorAll('#page button')].map(b=>b.textContent.trim()).slice(0,15));
console.log('ERR:',errors.slice(0,4));process.exit(0);
