import {JSDOM, VirtualConsole} from 'jsdom';
import {readFileSync} from 'node:fs';
import {FIXTURE} from './fixture.mjs';
const vc=new VirtualConsole();vc.on('jsdomError',e=>console.log('JSDOMERR',e.message));
const dom=new JSDOM(readFileSync('./public/index.html','utf8'),{runScripts:'dangerously',url:'https://localhost/',pretendToBeVisual:true,virtualConsole:vc});
const w=dom.window,doc=w.document;const sleep=ms=>new Promise(r=>setTimeout(r,ms));
await sleep(420);
w.eval(FIXTURE);
await sleep(60);
console.log('PERSIST_MODE =',w.eval('PERSIST_MODE'));
w.eval('localStorage.setItem=()=>{throw new Error("QuotaExceededError");}');
console.log('hasLS now =',w.eval('hasLS()'));
console.log('rawSet result =',await w.eval('rawSet("x","1")'));
w.eval('persist()');
await sleep(700);
console.log('PERSIST_FAIL =',w.eval('PERSIST_FAIL'));
console.log('snack text =',JSON.stringify(doc.getElementById('snack').textContent));
console.log('snack open =',doc.getElementById('snack').className);
process.exit(0);
