import {JSDOM, VirtualConsole} from 'jsdom';
import {readFileSync} from 'node:fs';
import {FIXTURE} from './fixture.mjs';
const dom=new JSDOM(readFileSync('./public/index.html','utf8'),{runScripts:'dangerously',url:'https://localhost/',pretendToBeVisual:true,virtualConsole:new VirtualConsole()});
const w=dom.window;const sleep=ms=>new Promise(r=>setTimeout(r,ms));
await sleep(420);
w.eval(FIXTURE);
await sleep(60);
w.eval(`S=buildSeedState();
 for(let i=0;i<5000;i++){const d=new Date(Date.UTC(2026,0,1+Math.floor(i/20)));const iso=d.toISOString().slice(0,10);
  S.transactions.push(blankTx({date:iso,reportingMonth:iso.slice(0,7),type:"business_income",status:"received",sourceName:"C",description:"r"+i,categoryId:"X",originalAmountCents:1000,convertedCadAmountCents:1000,accountId:"acct-primary"}));}`);
const r=w.eval(`(()=>{const p=document.createElement("div");const a=Date.now();renderLedger(p);const ms=Date.now()-a;
 return JSON.stringify({ms,rowsInDom:p.querySelectorAll("tbody tr").length,cells:p.querySelectorAll("tbody td").length,selects:p.querySelectorAll("tbody select").length,inputs:p.querySelectorAll("tbody input").length});})()`);
console.log('renderLedger:',r);
const r2=w.eval(`(()=>{const p=document.createElement("div");UI.ledger.pageSize=50;const a=Date.now();renderLedger(p);const ms=Date.now()-a;
 return JSON.stringify({ms,rowsInDom:p.querySelectorAll("tbody tr").length});})()`);
console.log('pageSize 50 :',r2);
process.exit(0);
