import {JSDOM, VirtualConsole} from 'jsdom';
import {readFileSync} from 'node:fs';
import {FIXTURE} from './fixture.mjs';
const dom=new JSDOM(readFileSync('./public/index.html','utf8'),{runScripts:'dangerously',url:'https://localhost/',pretendToBeVisual:true,virtualConsole:new VirtualConsole()});
const w=dom.window;const sleep=ms=>new Promise(r=>setTimeout(r,ms));
await sleep(420);
w.eval(FIXTURE);
await sleep(60);
w.eval(`S=buildSeedState();
 for(let i=0;i<5000;i++){const d=new Date(Date.UTC(2026,0,1+Math.floor(i/20)));const iso=d.toISOString().slice(0,10);
  S.transactions.push(blankTx({date:iso,reportingMonth:iso.slice(0,7),type:i%3===0?"business_expense":"business_income",status:i%3===0?"paid":"received",sourceName:"C"+(i%40),description:"row "+i,categoryId:"X",originalAmountCents:1000+i,convertedCadAmountCents:1000+i,accountId:"acct-primary"}));}`);
const t=(label,expr)=>{const a=Date.now();w.eval(expr);console.log(label.padEnd(34),(Date.now()-a)+'ms');};
t('ledgerFiltered(null)','ledgerFiltered(null)');
t('sortRows on 5000','sortRows(ledgerFiltered(null),materialCols(LEDGER_DEFAULT),{key:"date",dir:1})');
t('ledgerToolbar','ledgerToolbar({filter:null,title:"x"})');
t('running-balance map','(()=>{let run=0;return ledgerFiltered(null).map(x=>Object.assign(Object.create(Object.getPrototypeOf(x)),x,{__run:run+=1}));})()');
t('footer totals','(()=>{const r=ledgerFiltered(null);r.filter(isCounted).reduce((s,x)=>s+netImpactCents(x),0);})()');
t('dataTable 200 rows','dataTable({columns:materialCols(LEDGER_DEFAULT),rows:ledgerFiltered(null).slice(0,200),rowKey:r=>r.id,pinFirst:true,selectable:{sel:new Set(),onChange:()=>{}},sort:{key:"date",dir:1},onSort:()=>{}})');
t('dataTable 5000 rows','dataTable({columns:materialCols(LEDGER_DEFAULT),rows:ledgerFiltered(null),rowKey:r=>r.id,pinFirst:true,selectable:{sel:new Set(),onChange:()=>{}},sort:{key:"date",dir:1},onSort:()=>{}})');
t('FULL ledgerView','(()=>{const p=document.createElement("div");renderLedger(p);return p.childNodes.length;})()');
console.log('pageSize =',w.eval('UI.ledger.pageSize'));
process.exit(0);
